gql_server_conf:
  port: 8080

db_conf:
  username: root
  password: pass12345
  host: 1.2.3.4
  port: 8080
  database: database_name

admin_user:
  email: admin@email.com
  password: admin_password

jwt_conf:
  secret_key: secret_key
