// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Department struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewDepartment struct {
	Name string `json:"name"`
}
