// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Department struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type District struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Province *Province `json:"province"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewDepartment struct {
	Name string `json:"name"`
}

type NewDistrict struct {
	Name       string `json:"name"`
	ProvinceID string `json:"provinceId"`
}

type NewProvince struct {
	Name         string `json:"name"`
	DepartmentID string `json:"departmentId"`
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Province struct {
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	Department *Department `json:"department"`
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}
